version: 1.0.8
name: clue_ui_component
description: A UI library file used in the CLUe project, designed to enhance and streamline the development of dynamic and responsive user interfaces.
publisher: suprema.scloud@mysuprema.com
homepage: https://component.moon.supremainc.com/
repository: https://github.com/scloud-suprema/clueUiComponent

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  gap: ^3.0.1
  easy_rich_text: ^2.1.0
  calendar_date_picker2: ^0.5.3
  intl: ^0.19.0
  html: ^0.15.4
  loader_overlay: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.1.0
  build_runner: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
